# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12f083f9768d90b84768d3a778560bb4"
name = "Go-Digitial"
handle = "go-digitial"
application_url = "https://f50e-2405-201-41-e824-b0d3-1478-15ae-99c2.ngrok-free.app/auth"
embedded = false

[build]
dev_store_url = "stokeshub.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://f50e-2405-201-41-e824-b0d3-1478-15ae-99c2.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[app_preferences]
url = "https://f50e-2405-201-41-e824-b0d3-1478-15ae-99c2.ngrok-free.app/auth"


